### ISSUE TITLE
Not able to connect to Mailgun SMTP server Login Issue

### ISSUE THREAD

**Issue by bharathsai12** [azamuddin/mautic-mailgun-plugin#1]
Just wanted to  share theissue that is been caused when i am login in though my smtp user and password. getting error message

`535 5.7.0 Mailgun is not loving your login or password !! Expected response code 235 but got code "535",`

Any solution to resolve this issue, what is the port that need to be issued?

**Comment by azamuddin** [comment]
I think this is related to your mailgun credentials.
